final Map<String, String> positions = {
  'GK': 'Darvozabon',
  'CB': 'Markaziy himoyachi',
  'LCB': 'Chap markaziy himoyachi',
  'RCB': 'O‘ng markaziy himoyachi',
  'LB': 'Chap qanot himoyachi',
  'RB': 'O‘ng qanot himoyachi',
  'LWB': 'Chap wing-back',
  'RWB': 'O‘ng wing-back',
  'SW': 'So‘ruvchi himoyachi (sweeper)',
  'CDM': 'Himoyaviy yarim himoyachi',
  'CM': 'Markaziy yarim himoyachi',
  'CAM': 'Hujumkor markaziy yarim himoyachi',
  'LM': 'Chap yarim himoyachi',
  'RM': 'O‘ng yarim himoyachi',
  'LDM': 'Chap himoyaviy yarim himoyachi',
  'RDM': 'O‘ng himoyaviy yarim himoyachi',
  'LAM': 'Chap hujumkor yarim himoyachi',
  'RAM': 'O‘ng hujumkor yarim himoyachi',
  'CF': 'Markaziy hujumchi',
  'ST': 'Hujumchi',
  'LS': 'Chap hujumchi',
  'RS': 'O‘ng hujumchi',
  'LW': 'Chap vinger',
  'RW': 'O‘ng vinger',
  'WF': 'Qanot hujumchi',
  'DM': 'Himoyaviy yarim himoyachi',
  'AM': 'Hujumkor yarim himoyachi',
  'MF': 'Yarim himoyachi',
  'FW': 'Hujumchi (Forward)',
  'UL': 'Universal o‘yinchi',
};
